feat(improve read me): improve read me [Closes #5]
ITfiers/daisyui-react pull request #8
Opened 2021-10-14 06:20 UTC by Ahtisham101

2021-10-15 06:45 UTC, ejazahm3d requested changes

2021-10-15 06:45 UTC, ejazahm3d commented on README.md
> +- **Rectjs based**
Typo

2021-10-15 06:45 UTC, ejazahm3d commented on README.md
> +- **Tailwind CSS plugin**
This is not tailwind css plugin

2021-10-15 12:29 UTC, HassamSaeed approved these changes

2021-10-20 10:49 UTC, ejazahm3d approved these changes

2021-10-20 10:49 UTC, merged